# Generated by Django 2.0.5 on 2018-06-07 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('loaction', models.CharField(max_length=32)),
                ('date_issued', models.DateField()),
                ('date_returned', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('asset_tag', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('computer_name', models.CharField(max_length=32)),
                ('model', models.CharField(max_length=64)),
                ('os', models.CharField(max_length=32)),
                ('serial', models.CharField(max_length=32)),
                ('service_tag', models.CharField(max_length=16)),
                ('purchase_date', models.DateField()),
                ('warrenty_expiration', models.DateField()),
                ('last_update', models.DateField()),
                ('notes', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Deployed',
            fields=[
                ('asset_tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='manager.Inventory')),
                ('username', models.CharField(max_length=32)),
                ('location', models.CharField(max_length=32)),
                ('date_issued', models.DateField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.Group')),
            ],
        ),
        migrations.AddField(
            model_name='history',
            name='asset_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Inventory'),
        ),
    ]
