# Generated by Django 2.0.5 on 2018-06-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='computer_name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='last_update',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='model',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='notes',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='os',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='purchase_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='serial',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='service_tag',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='warrenty_expiration',
            field=models.DateField(null=True),
        ),
    ]
