# Generated by Django 2.0.6 on 2018-06-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20180625_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployed',
            name='group',
            field=models.CharField(max_length=32),
        ),
    ]
