# Generated by Django 2.0.6 on 2018-06-25 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20180625_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployed',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.Group'),
        ),
    ]
